### PR TITLE
Add example for gRPC-Server with Prometheus

### PR DESCRIPTION
**Pull request by fengzixu**
In the process of using it, I found that there is no corresponding example for this project. So I provide an example of gRPC Server and Prometheus with go-grpc-prometheus.

### CODE REVIEW

**Comment by fengzixu** [comment]
@mwitkow Ping :)

**Comment by fengzixu** [comment]
@mwitkow Ping :)

**Comment by fengzixu** [comment]
@hsaliak @mwitkow Is there anybody in the process of maintaining this project?

**Comment by hsaliak** [comment]
@mwitkow any update on this? This would serve as a very useful example.
@fengzixu i'll follow up with @mwitkow and other owners of this project.
gRPC-Ecosystem is meant to host a set of well maintained projects that are very useful for the community, so definitely we want to review this PR and evaluate.

**Comment by hsaliak** [comment]
Apologies! hit merge on the wrong PR by mistake, and so I have reverted this change.
@mwitkow it's over to you.

**Comment by fengzixu** [comment]
Why this PR is reverted? Is there anything else I need to add? @hsaliak

**Comment by hsaliak** [comment]
@fengzixu a new PR would be helpful yes.

**Pull request merged**
