### PR TITLE
adding make file and dep

### PR DESCRIPTION
**Pull request by domgreen**
Make it easier to work with the repo locally by ensuring it is easy to vet / fmt / test all code before putting out a PR.

### CODE REVIEW

**Comment by brancz** [comment]
Agreed with @Bplotka

**Comment by brancz** [comment]
lgtm on green

**Comment by Bplotka** [comment]
Travis err:
```
$ ./test_all.sh
/home/travis/.travis/job_stages: line 57: ./test_all.sh: No such file or directory
```

**Comment by domgreen** [comment]
Sorry my bad will fix

**Pull request merged**
