### PR TITLE
added target to metrics

### PR DESCRIPTION
**Pull request by dbarrosop**
Not sure if other people has a similar use case or if this is the right way to solve it but figured I'd open the PR to start discussing this.

I have an orchestrator that connects to several devices using a grpc_service that runs on each one of them. Because of that I found useful adding the `target` to the metrics. This way I can see the metrics broken down by device instead of just the aggregate.

### CODE REVIEW

**Comment by brancz** [comment]
In a full mesh this label would mean the cardinality of these metrics grow exponentially with the instances in the mesh. I understand that this data is worth a lot and I'm inclined to make it possible, but I don't think it's a good default, I think I'd be ok with it being opt-in, similar to histogram metrics on the server metrics. Wdyt @bwplotka ?

**Comment by bwplotka** [comment]
Agree. But even opt-in does not make sense if `target` changes a lot. You might be stepping into logging/even tracking use case rather.

**Comment by dbarrosop** [comment]
This makes sense if you don't have control over the servers (which is the case), otherwise, you end up duplicating this functionality yourself on the client side.

**Comment by bwplotka** [comment]
Hi 👋🏽 

Sorry for the massive, lag. We consolidating projects and moving to single repo where we have more control and awareness. We are moving this code base longer to https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v2 and we moved existing state of Prometheus middleware to https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v2/providers/openmetrics

This means that before we release `v2`  this is the best opportunity to shape new https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v2/providers/openmetrics with whatever we want to change in API 🤗 If you want to change something effectively long term, I would suggest switching your PR and rebasing it on https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v2/providers/openmetrics instead (notice `v2 `branch, not master!).

Sorry for the confusion, but it's needed for the project sustainability. Cheers!

**Comment by dbarrosop** [comment]
I am good reworking this PR but I'd need some guidance on how you'd like this implemented. I still need the functionality and have been using my own fork in production but I'd be very interested in having this upstreamed.

Thanks!

**Pull request closed without merging**
