### PR TITLE
Fix grammar mistakes in readme

### PR DESCRIPTION
**Pull request by dominikh**

### CODE REVIEW

**Comment by knweiss** [comment]
The 2nd hunk is fixed in master already. The first trivial hunk is still required. Merge?

**Comment by Bplotka** [comment]
I rebased manually using Github UI, but it seems I made Googlebot sad by that.

I guess it's fair to have @dominikh "ok" for it, but the change is quite straightforward.

**Comment by dominikh** [comment]
This is a single character documentation fix that took 1.5 years, involved four people and two bots, and now contains an unnecessary merge commit instead of a straightforward rebase.

Nothing about this is "ok", but legally speaking I'm fine with this being merged…

**Comment by Bplotka** [comment]
Lmao

**Pull request merged**
